using Microsoft.AspNetCore.Mvc;

namespace ShortenUrl.API.Controllers;

[ApiController]
[Route("[controller]")]
public class ShortenUrlController : ControllerBase
{
    [HttpPost]
    [ProducesResponseType(StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> ShortenUrl([FromBody] string originalUrl)
    {
        // Placeholder implementation
        var shortCode = "abc123"; // This would be generated by the application logic
        return Ok(new { ShortCode = shortCode });
    }

    [HttpGet("{shortCode}")]
    [ProducesResponseType(StatusCodes.Status302Found)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> RedirectToOriginalUrl(string shortCode)
    {
        return Ok(new { OriginalUrl = shortCode });
    }
}